// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: translator/scion_paths/scionproto/pathsrv.proto

package pathsrv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A single path segment
type PathSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	Mtu           uint32                 `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Interfaces    []uint32               `protobuf:"varint,3,rep,packed,name=interfaces,proto3" json:"interfaces,omitempty"`
	Expiration    string                 `protobuf:"bytes,4,opt,name=expiration,proto3" json:"expiration,omitempty"` // ISO string for simplicity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathSegment) Reset() {
	*x = PathSegment{}
	mi := &file_translator_scion_paths_scionproto_pathsrv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathSegment) ProtoMessage() {}

func (x *PathSegment) ProtoReflect() protoreflect.Message {
	mi := &file_translator_scion_paths_scionproto_pathsrv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathSegment.ProtoReflect.Descriptor instead.
func (*PathSegment) Descriptor() ([]byte, []int) {
	return file_translator_scion_paths_scionproto_pathsrv_proto_rawDescGZIP(), []int{0}
}

func (x *PathSegment) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *PathSegment) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *PathSegment) GetInterfaces() []uint32 {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *PathSegment) GetExpiration() string {
	if x != nil {
		return x.Expiration
	}
	return ""
}

// Request for paths from source to destination IA
type PathsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIa         string                 `protobuf:"bytes,1,opt,name=src_ia,json=srcIa,proto3" json:"src_ia,omitempty"`
	DstIa         string                 `protobuf:"bytes,2,opt,name=dst_ia,json=dstIa,proto3" json:"dst_ia,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathsRequest) Reset() {
	*x = PathsRequest{}
	mi := &file_translator_scion_paths_scionproto_pathsrv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathsRequest) ProtoMessage() {}

func (x *PathsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translator_scion_paths_scionproto_pathsrv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathsRequest.ProtoReflect.Descriptor instead.
func (*PathsRequest) Descriptor() ([]byte, []int) {
	return file_translator_scion_paths_scionproto_pathsrv_proto_rawDescGZIP(), []int{1}
}

func (x *PathsRequest) GetSrcIa() string {
	if x != nil {
		return x.SrcIa
	}
	return ""
}

func (x *PathsRequest) GetDstIa() string {
	if x != nil {
		return x.DstIa
	}
	return ""
}

// Response contains one or more path segments
type PathsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []*PathSegment         `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathsResponse) Reset() {
	*x = PathsResponse{}
	mi := &file_translator_scion_paths_scionproto_pathsrv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathsResponse) ProtoMessage() {}

func (x *PathsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translator_scion_paths_scionproto_pathsrv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathsResponse.ProtoReflect.Descriptor instead.
func (*PathsResponse) Descriptor() ([]byte, []int) {
	return file_translator_scion_paths_scionproto_pathsrv_proto_rawDescGZIP(), []int{2}
}

func (x *PathsResponse) GetPaths() []*PathSegment {
	if x != nil {
		return x.Paths
	}
	return nil
}

var File_translator_scion_paths_scionproto_pathsrv_proto protoreflect.FileDescriptor

const file_translator_scion_paths_scionproto_pathsrv_proto_rawDesc = "" +
	"\n" +
	"/translator/scion_paths/scionproto/pathsrv.proto\x12\apathsrv\"q\n" +
	"\vPathSegment\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\x12\x10\n" +
	"\x03mtu\x18\x02 \x01(\rR\x03mtu\x12\x1e\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\rR\n" +
	"interfaces\x12\x1e\n" +
	"\n" +
	"expiration\x18\x04 \x01(\tR\n" +
	"expiration\"<\n" +
	"\fPathsRequest\x12\x15\n" +
	"\x06src_ia\x18\x01 \x01(\tR\x05srcIa\x12\x15\n" +
	"\x06dst_ia\x18\x02 \x01(\tR\x05dstIa\";\n" +
	"\rPathsResponse\x12*\n" +
	"\x05paths\x18\x01 \x03(\v2\x14.pathsrv.PathSegmentR\x05paths2E\n" +
	"\vPathService\x126\n" +
	"\x05Paths\x12\x15.pathsrv.PathsRequest\x1a\x16.pathsrv.PathsResponseB+Z)translator/scion_paths/scionproto;pathsrvb\x06proto3"

var (
	file_translator_scion_paths_scionproto_pathsrv_proto_rawDescOnce sync.Once
	file_translator_scion_paths_scionproto_pathsrv_proto_rawDescData []byte
)

func file_translator_scion_paths_scionproto_pathsrv_proto_rawDescGZIP() []byte {
	file_translator_scion_paths_scionproto_pathsrv_proto_rawDescOnce.Do(func() {
		file_translator_scion_paths_scionproto_pathsrv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_translator_scion_paths_scionproto_pathsrv_proto_rawDesc), len(file_translator_scion_paths_scionproto_pathsrv_proto_rawDesc)))
	})
	return file_translator_scion_paths_scionproto_pathsrv_proto_rawDescData
}

var file_translator_scion_paths_scionproto_pathsrv_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_translator_scion_paths_scionproto_pathsrv_proto_goTypes = []any{
	(*PathSegment)(nil),   // 0: pathsrv.PathSegment
	(*PathsRequest)(nil),  // 1: pathsrv.PathsRequest
	(*PathsResponse)(nil), // 2: pathsrv.PathsResponse
}
var file_translator_scion_paths_scionproto_pathsrv_proto_depIdxs = []int32{
	0, // 0: pathsrv.PathsResponse.paths:type_name -> pathsrv.PathSegment
	1, // 1: pathsrv.PathService.Paths:input_type -> pathsrv.PathsRequest
	2, // 2: pathsrv.PathService.Paths:output_type -> pathsrv.PathsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_translator_scion_paths_scionproto_pathsrv_proto_init() }
func file_translator_scion_paths_scionproto_pathsrv_proto_init() {
	if File_translator_scion_paths_scionproto_pathsrv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_translator_scion_paths_scionproto_pathsrv_proto_rawDesc), len(file_translator_scion_paths_scionproto_pathsrv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_translator_scion_paths_scionproto_pathsrv_proto_goTypes,
		DependencyIndexes: file_translator_scion_paths_scionproto_pathsrv_proto_depIdxs,
		MessageInfos:      file_translator_scion_paths_scionproto_pathsrv_proto_msgTypes,
	}.Build()
	File_translator_scion_paths_scionproto_pathsrv_proto = out.File
	file_translator_scion_paths_scionproto_pathsrv_proto_goTypes = nil
	file_translator_scion_paths_scionproto_pathsrv_proto_depIdxs = nil
}
